### ISSUE TITLE
Project Roadmap and Ideas

### ISSUE THREAD

**Issue by abhi18av** [abhi18av/robohash-js-base#3]

**Comment by abhi18av** [comment]
m1.0

- [x] fetch image using a hard-coded name in the url
- [x] use a function component to achieve this 
- [ ] refactor this into a class component
- [ ] revert this merge to restore the function component
